# MediaWiki with MariaDB and automatic backups
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3.5'
services:
  mediawiki:
    image: sundin-mediawiki
    ports:
      - 8080:80
    volumes:
      - ./settings/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./settings:/external_includes
      - ./images:/var/www/html/images
    restart: always
  database:
    image: mariadb:10.1.39
    restart: always
    # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    env_file:
      - .env
  backup:
    image: deitch/mysql-backup@sha256:03a414973e8de82d3909bbe9b282d032da13eacc89fa768ce111d245d75e854e
    restart: always
    volumes:
      - ./db_backup:/db
    env_file:
      - .env
    environment:
      - DB_SERVER=database
      - DB_PORT=3306
      - DB_DUMP_TARGET=/db
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=+1
  parsoid:
    image: thenets/parsoid:0.9.0
    ports:
      - 8081:8000
    environment:
      - PARSOID_DOMAIN_mediawiki=http://mediawiki/api.php
networks:
  default:
    name: mediawiki-network
    driver: bridge
